//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Translation
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspnetMvcDemo.Translation.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسجيل مصنع جديد.
        /// </summary>
        internal static string Create_Factory
        {
            get
            {
                return ResourceManager.GetString("Create Factory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string Login_to_Your_Account
        {
            get
            {
                return ResourceManager.GetString("Login to Your Account", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        internal static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مراقبة جودة مصانع الخرسانة والبلوك.
        /// </summary>
        internal static string Quanlity_Control_System_for_Concrete
        {
            get
            {
                return ResourceManager.GetString("Quanlity Control System for Concrete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        internal static string Remember_me
        {
            get
            {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        internal static string Sign_In
        {
            get
            {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التسجيل كمصنع جديد.
        /// </summary>
        internal static string Signup_as_new_Factory
        {
            get
            {
                return ResourceManager.GetString("Signup as new Factory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string User_name
        {
            get
            {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
    }
}
