//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertInfraction
    {
        public int ID { get; set; }
        public Nullable<int> AlertID { get; set; }
        public Nullable<int> InfractionID { get; set; }
    
        public virtual Alert Alert { get; set; }
        public virtual Infraction Infraction { get; set; }
    }
}
