//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockInfraction
    {
        public int id { get; set; }
        public Nullable<int> factory_id { get; set; }
        public Nullable<int> SampleNo { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public Nullable<bool> AdminApproved { get; set; }
        public Nullable<bool> MonitorApproved { get; set; }
        public Nullable<bool> Monitor2Approved { get; set; }
        public Nullable<int> Alert_id { get; set; }
    }
}
