//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockTestResult
    {
        public int id { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> Minfaceshell { get; set; }
        public Nullable<double> NetArea { get; set; }
        public Nullable<double> GrossArea { get; set; }
        public Nullable<double> load { get; set; }
        public Nullable<double> compbetarea { get; set; }
        public Nullable<double> compgrossarea { get; set; }
        public Nullable<double> strengthrequirement { get; set; }
        public Nullable<double> AvgNetArea { get; set; }
        public Nullable<double> AvgGrossArea { get; set; }
        public Nullable<int> sampleNumber { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public Nullable<double> height { get; set; }
    }
}
