//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakSampleFactory
    {
        public int id { get; set; }
        public Nullable<int> SampleNumber { get; set; }
        public string Cube1Img1 { get; set; }
        public string Cube1Img2 { get; set; }
        public string Cube2Img1 { get; set; }
        public string Cube2Img2 { get; set; }
        public string Cube3Img1 { get; set; }
        public string Cube3Img2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
