//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckEquipmentRequirementsOfFactory
    {
        public int ID { get; set; }
        public string InputValue { get; set; }
        public int CheckEquipmentRequirementsId { get; set; }
        public int FactoryEvaluationReportId { get; set; }
    
        public virtual CheckEquipmentRequirement CheckEquipmentRequirement { get; set; }
        public virtual FactoryEvaluationReport FactoryEvaluationReport { get; set; }
    }
}
