//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationSubItem
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Degree { get; set; }
        public Nullable<int> parent_id { get; set; }
    }
}
