//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationResult
    {
        public int id { get; set; }
        public Nullable<int> factory_id { get; set; }
        public Nullable<double> Result_One { get; set; }
        public Nullable<double> Result_Two { get; set; }
        public Nullable<double> Result_three { get; set; }
        public Nullable<double> Total_Result { get; set; }
    }
}
