//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compaction
    {
        public int SampleNo { get; set; }
        public int GeneralSamleTypeId { get; set; }
        public Nullable<double> Comp1 { get; set; }
        public Nullable<double> Comp2 { get; set; }
        public Nullable<double> Comp3 { get; set; }
        public Nullable<double> CRatio { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> AsphaltTypeId { get; set; }
        public Nullable<int> SoilTypeId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> GehaID { get; set; }
    }
}
