//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteSample1
    {
        public long ReportNo { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string FactoryName { get; set; }
        public string FactoryLocation { get; set; }
        public string MixerNumber { get; set; }
        public Nullable<long> VisitNumber { get; set; }
        public Nullable<long> SampleNumber { get; set; }
        public string TruckNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string ClientName { get; set; }
        public string VisitLocation { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ConcreteRank { get; set; }
        public Nullable<double> ConcreteTemperture { get; set; }
        public Nullable<double> WaterTemperature { get; set; }
        public Nullable<double> WeatherTemperture { get; set; }
        public Nullable<double> DownAmount { get; set; }
        public string CementType { get; set; }
        public string CementSource { get; set; }
        public string AdditionType { get; set; }
        public Nullable<double> AdditionAmount { get; set; }
        public Nullable<double> CementWeight { get; set; }
        public Nullable<double> WaterWieght { get; set; }
        public Nullable<double> WashedSandWeight { get; set; }
        public Nullable<double> WhiteSandWeight { get; set; }
        public Nullable<double> Rubble3by4 { get; set; }
        public Nullable<double> Rubble3by8 { get; set; }
        public Nullable<bool> IsCleanUsage { get; set; }
        public Nullable<bool> IsBasicUsage { get; set; }
        public Nullable<bool> IsColumnUsage { get; set; }
        public Nullable<bool> IsRoofUsage { get; set; }
        public Nullable<bool> IsOtherUsage { get; set; }
        public Nullable<bool> IsCleanLocation { get; set; }
        public Nullable<bool> IsDustControlInStation { get; set; }
        public Nullable<bool> IsRokamSummer { get; set; }
        public Nullable<bool> IsLabEngineer { get; set; }
        public Nullable<bool> IsMoldanatInTrucks { get; set; }
        public Nullable<bool> IsPeopleSafty { get; set; }
        public Nullable<int> SampledBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public string InvoicePhoto { get; set; }
        public string CleanDocPath { get; set; }
        public string DustDocPath { get; set; }
        public string SummerDocPath { get; set; }
        public string LabDocPath { get; set; }
        public string TruckDocPath { get; set; }
        public string SafteyDocPath { get; set; }
        public string OtherReason { get; set; }
        public string CleanDocNote { get; set; }
        public string DustDocNote { get; set; }
        public string SummerDocNote { get; set; }
        public string LabDocNote { get; set; }
        public string TruckDocNote { get; set; }
        public string SafteyDocNote { get; set; }
        public Nullable<bool> labdeliver { get; set; }
        public string TempretureDocPath { get; set; }
        public string DownAmountDocPath { get; set; }
        public string concretemixPath { get; set; }
    }
}
