//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteTestSample
    {
        public int SampleNo { get; set; }
        public Nullable<double> Wg1 { get; set; }
        public Nullable<double> Wg2 { get; set; }
        public Nullable<double> Wg3 { get; set; }
        public Nullable<double> Wg4 { get; set; }
        public Nullable<double> Wg5 { get; set; }
        public Nullable<double> Wg6 { get; set; }
        public Nullable<System.DateTime> CrushingDate1 { get; set; }
        public Nullable<System.DateTime> CrushingDate2 { get; set; }
        public Nullable<int> AgeDays1 { get; set; }
        public Nullable<int> AgeDays2 { get; set; }
        public Nullable<double> LoadedAreaMM1 { get; set; }
        public Nullable<double> LoadedAreaMM2 { get; set; }
        public Nullable<double> Kn1 { get; set; }
        public Nullable<double> Kn2 { get; set; }
        public Nullable<double> Kn3 { get; set; }
        public Nullable<double> Kn4 { get; set; }
        public Nullable<double> Kn5 { get; set; }
        public Nullable<double> Kn6 { get; set; }
        public Nullable<double> Nmm1 { get; set; }
        public Nullable<double> Nmm2 { get; set; }
        public Nullable<double> Nmm3 { get; set; }
        public Nullable<double> Nmm4 { get; set; }
        public Nullable<double> Nmm5 { get; set; }
        public Nullable<double> Nmm6 { get; set; }
        public Nullable<double> Avg1 { get; set; }
        public Nullable<double> Avg2 { get; set; }
    }
}
