//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsMaterialSup
    {
        public int ID { get; set; }
        public Nullable<int> ConClsMaterialSupCategoryIdq { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Location { get; set; }
        public string TypeofMaterial { get; set; }
        public Nullable<int> FactoryId { get; set; }
    }
}
