//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsLabEquipment
    {
        public int ID { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public Nullable<int> ClsYear { get; set; }
        public string MadeYear { get; set; }
        public string MadeFactoryCompany { get; set; }
        public Nullable<int> MachineType { get; set; }
        public Nullable<int> SpeedControl { get; set; }
        public Nullable<int> TempControl1 { get; set; }
        public Nullable<int> TempControl2 { get; set; }
        public Nullable<int> TempControl3 { get; set; }
    }
}
