//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteInspectorLogError
    {
        public int SampleNo { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string Error { get; set; }
        public Nullable<System.Guid> InspectorUserId { get; set; }
    }
}
