//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteSample
    {
        public int SampleNo { get; set; }
        public string FactoryName { get; set; }
        public Nullable<int> PlantNumber { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public Nullable<double> SampleTime { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string TrucksNumber { get; set; }
        public string Client { get; set; }
        public string Location { get; set; }
        public string ConcreteRank { get; set; }
        public Nullable<int> ConcreteTemperture { get; set; }
        public Nullable<int> WeatherTemperture { get; set; }
        public Nullable<int> AmountofLand { get; set; }
        public string AcementType { get; set; }
        public string AcementSource { get; set; }
        public string AdditionTypes { get; set; }
        public Nullable<double> AdditionAmount { get; set; }
        public Nullable<bool> IsCleanUsage { get; set; }
        public Nullable<bool> IsBasicUsage { get; set; }
        public Nullable<bool> IsColumnUsage { get; set; }
        public Nullable<bool> IsRoofUsage { get; set; }
        public Nullable<bool> IsOtherUsage { get; set; }
        public Nullable<int> AcementWeight { get; set; }
        public Nullable<int> WaterWieght { get; set; }
        public Nullable<int> WashedSandWeight { get; set; }
        public string SizeFourbyThree { get; set; }
        public string SizeEightByThree { get; set; }
        public Nullable<bool> IsCleanLocation { get; set; }
        public Nullable<bool> IsDustControlInStation { get; set; }
        public Nullable<bool> IsRokamSummar { get; set; }
        public Nullable<bool> IsLabEngineer { get; set; }
        public Nullable<bool> IsMoldanatInTrunks { get; set; }
        public Nullable<bool> IsPeopeSafty { get; set; }
        public Nullable<System.Guid> SampledBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> WhiteSandWeight { get; set; }
        public Nullable<int> WaterTemperature { get; set; }
        public Nullable<double> Resist7days { get; set; }
        public Nullable<double> Resist28days { get; set; }
        public string AmanaSampleNo { get; set; }
    }
}
