//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcreteSamplesWorkFlow
    {
        public int SampleNo { get; set; }
        public Nullable<System.DateTime> SampledDate { get; set; }
        public Nullable<System.Guid> SampledBy { get; set; }
        public Nullable<System.DateTime> ReviewedSampleDate { get; set; }
        public Nullable<System.Guid> ReviewedSampleBy { get; set; }
        public Nullable<System.Guid> TestedBy { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public Nullable<System.Guid> ReviewedTestBy { get; set; }
        public Nullable<System.DateTime> ReviewedTestDate { get; set; }
        public Nullable<bool> IsFinished { get; set; }
    }
}
