//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsEvalPerformControl
    {
        public int FactoryId { get; set; }
        public int ConClsYear { get; set; }
        public string TempGeneralComment { get; set; }
        public string TempQualtyMaxComment { get; set; }
        public string TempQualtyMinComment1 { get; set; }
        public string Slump { get; set; }
        public string CompressiveStrength { get; set; }
    }
}
