//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsLabTestPractice
    {
        public int FactoryId { get; set; }
        public int ClsYear { get; set; }
        public Nullable<bool> MethodCuringWater { get; set; }
        public Nullable<bool> MethodCuringTempl { get; set; }
        public Nullable<bool> MehodTestingSurface { get; set; }
        public Nullable<bool> MethodRatLoading { get; set; }
        public Nullable<bool> ProperProtection { get; set; }
    }
}
