//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsLabAdmixture
    {
        public int FactoryId { get; set; }
        public int ClsYear { get; set; }
        public Nullable<bool> IsTechniqcalSheet { get; set; }
        public Nullable<int> TrialMixesEvalutePeriodicId { get; set; }
        public Nullable<double> TrialMixesEvalutePeriodicWeight { get; set; }
    }
}
