//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConClsMixDesign
    {
        public int FactoryId { get; set; }
        public int ClsYear { get; set; }
        public Nullable<double> MixResult40 { get; set; }
        public Nullable<double> MixResult35 { get; set; }
        public Nullable<double> MixResult30 { get; set; }
        public Nullable<double> MixResult20 { get; set; }
        public Nullable<double> CementKg40 { get; set; }
        public Nullable<double> CementKg35 { get; set; }
        public Nullable<double> CementKg30 { get; set; }
        public Nullable<double> CementKg20 { get; set; }
        public Nullable<double> HotWater40 { get; set; }
        public Nullable<double> HotWater35 { get; set; }
        public Nullable<double> HotWater30 { get; set; }
        public Nullable<double> HotWater20 { get; set; }
        public Nullable<double> Rookam3by4Kg40 { get; set; }
        public Nullable<double> Rookam3by4Kg35 { get; set; }
        public Nullable<double> Rookam3by4Kg30 { get; set; }
        public Nullable<double> Rookam3by4Kg20 { get; set; }
        public Nullable<double> Rookam3by8Kg40 { get; set; }
        public Nullable<double> Rookam3by8Kg35 { get; set; }
        public Nullable<double> Rookam3by8Kg30 { get; set; }
        public Nullable<double> Rookam3by8Kg20 { get; set; }
        public Nullable<double> SelicaSandKg40 { get; set; }
        public Nullable<double> SelicaSandKg35 { get; set; }
        public Nullable<double> SelicaSandKg30 { get; set; }
        public Nullable<double> SelicaSandKg20 { get; set; }
        public Nullable<double> WachingSandKg40 { get; set; }
        public Nullable<double> WachingSandKg35 { get; set; }
        public Nullable<double> WachingSandKg30 { get; set; }
        public Nullable<double> WachingSandKg20 { get; set; }
        public Nullable<double> RP264Litter40 { get; set; }
        public Nullable<double> RP264Litter35 { get; set; }
        public Nullable<double> RP264Litter30 { get; set; }
        public Nullable<double> RP264Litter20 { get; set; }
    }
}
