//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorRetFlow
    {
        public string RequestNumber { get; set; }
        public Nullable<bool> IsContractorSubmit { get; set; }
        public Nullable<System.DateTime> ContractorSubmit { get; set; }
        public Nullable<bool> IsGMAccept { get; set; }
        public Nullable<System.DateTime> GMAccept { get; set; }
        public string Notes { get; set; }
        public string TestsTypes { get; set; }
    }
}
