//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lang { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string OwnerName { get; set; }
        public string ResponsibleManager { get; set; }
        public string ResponsibleManagerCertified { get; set; }
        public string TechManager { get; set; }
        public string TechManagerCertified { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string ProductEnergy { get; set; }
        public string DailyProductRating { get; set; }
        public Nullable<int> CodeNo { get; set; }
    }
}
