//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory1
    {
        public int FactoryID { get; set; }
        public string FactoryName { get; set; }
        public string FactoryEngName { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AddressDetail { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ManagerRespons { get; set; }
        public string ManagerCert { get; set; }
        public string ManagerTech { get; set; }
        public string ManagerTechCert { get; set; }
        public string ProductivityPower { get; set; }
        public string AvgDailyProd { get; set; }
        public Nullable<double> StandardDiviation { get; set; }
        public Nullable<double> StandardDiv30 { get; set; }
        public Nullable<double> StandardDiv35 { get; set; }
        public Nullable<double> StandardDiv40 { get; set; }
    }
}
