//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory11
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factory11()
        {
            this.ConcreteMixingDesigns = new HashSet<ConcreteMixingDesign>();
            this.Alerts = new HashSet<Alert>();
            this.Pledges = new HashSet<Pledge>();
            this.MixingStationsAnswersOfFactories = new HashSet<MixingStationsAnswersOfFactory>();
            this.FactoryEvaluationReports = new HashSet<FactoryEvaluationReport>();
            this.ReportResults = new HashSet<ReportResult>();
            this.OpenAndCloseFactories = new HashSet<OpenAndCloseFactory>();
            this.OpenCloseFactories = new HashSet<OpenCloseFactory>();
            this.TechnicalReports = new HashSet<TechnicalReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<double> ProductionCapacity { get; set; }
        public Nullable<double> DailyProductionRate { get; set; }
        public Nullable<int> NumberofMixers { get; set; }
        public Nullable<int> NumberofTrucks { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string MailBox { get; set; }
        public string Email { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerPhoneNumber { get; set; }
        public string ManagerName { get; set; }
        public string ManagerPhoneNumber { get; set; }
        public string ManagerEmail { get; set; }
        public string ManagerExperience { get; set; }
        public string EngineerName { get; set; }
        public string EngineerPhoneNumber { get; set; }
        public string EngineerEmail { get; set; }
        public string EngineerExperience { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string Location { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<bool> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConcreteMixingDesign> ConcreteMixingDesigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pledge> Pledges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixingStationsAnswersOfFactory> MixingStationsAnswersOfFactories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactoryEvaluationReport> FactoryEvaluationReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportResult> ReportResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenAndCloseFactory> OpenAndCloseFactories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenCloseFactory> OpenCloseFactories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalReport> TechnicalReports { get; set; }
    }
}
