//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryEvaluationReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactoryEvaluationReport()
        {
            this.CheckEquipmentRequirementsOfFactories = new HashSet<CheckEquipmentRequirementsOfFactory>();
            this.ReportResults = new HashSet<ReportResult>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int FactoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckEquipmentRequirementsOfFactory> CheckEquipmentRequirementsOfFactories { get; set; }
        public virtual Factory11 Factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportResult> ReportResults { get; set; }
    }
}
