//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infraction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infraction()
        {
            this.AlertInfractions = new HashSet<AlertInfraction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public Nullable<bool> Temperature { get; set; }
        public Nullable<bool> Landing { get; set; }
        public Nullable<bool> C8Day { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<long> SampleNo { get; set; }
        public Nullable<bool> AdminApproved { get; set; }
        public Nullable<bool> MonitorApproved { get; set; }
        public Nullable<bool> IsCleanLocation { get; set; }
        public Nullable<bool> NotUsingMixtureofClass { get; set; }
        public Nullable<bool> AbsenceofDevice { get; set; }
        public Nullable<bool> HardwareNotCalibrated { get; set; }
        public Nullable<bool> InsufficientRecords { get; set; }
        public Nullable<bool> Monitor2Approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertInfraction> AlertInfractions { get; set; }
    }
}
