//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCheck
    {
        public int id { get; set; }
        public string Machine_Name { get; set; }
        public string Check_duration { get; set; }
        public string Machine_Check_Date { get; set; }
    }
}
