//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapUserProject
    {
        public int ProjectId { get; set; }
        public System.Guid ContractorId { get; set; }
        public Nullable<System.Guid> ProjectUserId { get; set; }
    }
}
