//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarshalAspMixDesApp
    {
        public int SampleNo { get; set; }
        public bool IsLabEngineer { get; set; }
        public Nullable<double> Pin1 { get; set; }
        public Nullable<double> Pin2 { get; set; }
        public Nullable<double> Pin3 { get; set; }
        public Nullable<double> Pin4 { get; set; }
        public Nullable<double> Pin5 { get; set; }
        public Nullable<double> Filler { get; set; }
        public Nullable<double> PinTot { get; set; }
        public Nullable<double> S11B2P1 { get; set; }
        public Nullable<double> S11B2P2 { get; set; }
        public Nullable<double> S11B2P3 { get; set; }
        public Nullable<double> S11B2P4 { get; set; }
        public Nullable<double> S11B2P5 { get; set; }
        public Nullable<double> S11B2F { get; set; }
        public Nullable<double> S11B2Tot { get; set; }
        public Nullable<double> S1P1 { get; set; }
        public Nullable<double> S1P2 { get; set; }
        public Nullable<double> S1P3 { get; set; }
        public Nullable<double> S1P4 { get; set; }
        public Nullable<double> S1P5 { get; set; }
        public Nullable<double> S1F { get; set; }
        public Nullable<double> TotS1 { get; set; }
        public Nullable<double> S3B4P1 { get; set; }
        public Nullable<double> S3B4P2 { get; set; }
        public Nullable<double> S3B4P3 { get; set; }
        public Nullable<double> S3B4P4 { get; set; }
        public Nullable<double> S3B4P5 { get; set; }
        public Nullable<double> S3B4F { get; set; }
        public Nullable<double> TotS3B4 { get; set; }
        public Nullable<double> S1B2P1 { get; set; }
        public Nullable<double> S1B2P2 { get; set; }
        public Nullable<double> S1B2P3 { get; set; }
        public Nullable<double> S1B2P4 { get; set; }
        public Nullable<double> S1B2P5 { get; set; }
        public Nullable<double> S1B2F { get; set; }
        public Nullable<double> TotS1B2 { get; set; }
        public Nullable<double> S3B8P1 { get; set; }
        public Nullable<double> S3B8P2 { get; set; }
        public Nullable<double> S3B8P3 { get; set; }
        public Nullable<double> S3B8P4 { get; set; }
        public Nullable<double> S3B8P5 { get; set; }
        public Nullable<double> S3B8F { get; set; }
        public Nullable<double> TotS3B8 { get; set; }
        public Nullable<double> S4P1 { get; set; }
        public Nullable<double> S4P2 { get; set; }
        public Nullable<double> S4P3 { get; set; }
        public Nullable<double> S4P4 { get; set; }
        public Nullable<double> S4P5 { get; set; }
        public Nullable<double> S4F { get; set; }
        public Nullable<double> S4Tot { get; set; }
        public Nullable<double> S10P1 { get; set; }
        public Nullable<double> S10P2 { get; set; }
        public Nullable<double> S10P3 { get; set; }
        public Nullable<double> S10P4 { get; set; }
        public Nullable<double> S10P5 { get; set; }
        public Nullable<double> S10F { get; set; }
        public Nullable<double> S10Tot { get; set; }
        public Nullable<double> S40P1 { get; set; }
        public Nullable<double> S40P2 { get; set; }
        public Nullable<double> S40P3 { get; set; }
        public Nullable<double> S40P4 { get; set; }
        public Nullable<double> S40P5 { get; set; }
        public string S40F { get; set; }
        public Nullable<double> S40Tot { get; set; }
        public Nullable<double> S80P1 { get; set; }
        public Nullable<double> S80P2 { get; set; }
        public Nullable<double> S80P3 { get; set; }
        public Nullable<double> S80P4 { get; set; }
        public Nullable<double> S80P5 { get; set; }
        public string S80F { get; set; }
        public Nullable<double> S80Tot { get; set; }
        public Nullable<double> S200P1 { get; set; }
        public Nullable<double> S200P2 { get; set; }
        public Nullable<double> S200P3 { get; set; }
        public Nullable<double> S200P4 { get; set; }
        public Nullable<double> S200P5 { get; set; }
        public Nullable<double> S200F { get; set; }
        public Nullable<double> S200Tot { get; set; }
        public Nullable<double> Pb { get; set; }
        public Nullable<double> Gmb { get; set; }
        public Nullable<double> Gmm { get; set; }
        public Nullable<double> AirVoid { get; set; }
        public Nullable<double> VoidsFilled { get; set; }
        public Nullable<double> Stability30 { get; set; }
        public Nullable<double> LossOfStability { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<double> PI { get; set; }
        public Nullable<double> Gsb { get; set; }
        public Nullable<double> SandEquivalent { get; set; }
        public Nullable<double> AbrasionValue { get; set; }
        public Nullable<double> ClayAndLumps { get; set; }
        public Nullable<double> ThinAndElongated { get; set; }
        public Nullable<double> Soundness { get; set; }
        public Nullable<double> CrushedParticles_CA { get; set; }
        public Nullable<double> Crushedparticles_FA { get; set; }
        public Nullable<double> Coating { get; set; }
        public Nullable<double> AggFactor { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<int> AttemptNo { get; set; }
        public Nullable<bool> Fail { get; set; }
        public Nullable<bool> FatBlend { get; set; }
        public Nullable<bool> FatSE { get; set; }
        public Nullable<bool> FatAValue { get; set; }
        public Nullable<bool> FatCL { get; set; }
        public Nullable<bool> FatTAE { get; set; }
        public Nullable<bool> FatSoundness { get; set; }
        public Nullable<bool> FatCA { get; set; }
        public Nullable<bool> FatFA { get; set; }
        public Nullable<bool> FatCoating { get; set; }
        public Nullable<bool> FatPI { get; set; }
        public Nullable<bool> FatAV { get; set; }
        public Nullable<bool> FatVF { get; set; }
        public Nullable<bool> FatS30 { get; set; }
        public Nullable<bool> FatLOS { get; set; }
        public Nullable<bool> FatFlow { get; set; }
        public Nullable<int> PlantLocationId { get; set; }
        public Nullable<int> AsphaltTypesId { get; set; }
        public string ContSampleRequest { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
    }
}
