//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarshalMixDesign
    {
        public int SampleNo { get; set; }
        public Nullable<int> PlantNo { get; set; }
        public Nullable<int> TypeNum { get; set; }
        public Nullable<int> SupressIt { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> PreviousDateEnd { get; set; }
        public string Approved_Date_H { get; set; }
        public string End_Date_H { get; set; }
        public Nullable<System.DateTime> DateEndExtended { get; set; }
        public string DateEndExtended_H { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> MaxAsphaltRatio { get; set; }
        public Nullable<double> MinAsphaltRatio { get; set; }
        public Nullable<double> StabilityAfter30Min { get; set; }
        public Nullable<double> AGS_LossOfStability { get; set; }
        public Nullable<double> MaxFlow { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<double> MaxAirVoids { get; set; }
        public Nullable<double> AirVoids { get; set; }
        public Nullable<double> MaxFilledVoids { get; set; }
        public Nullable<double> FilledVoids { get; set; }
        public Nullable<double> AggregateFilledVoids { get; set; }
        public Nullable<int> CompTop { get; set; }
        public Nullable<int> CompBot { get; set; }
        public Nullable<double> Gmm { get; set; }
        public Nullable<double> Gmb { get; set; }
        public Nullable<double> Gsb { get; set; }
        public Nullable<double> SIEVE_11By2 { get; set; }
        public Nullable<double> SIEVE_1 { get; set; }
        public Nullable<double> SIEVE_3By4 { get; set; }
        public Nullable<double> SIEVE_1By2 { get; set; }
        public Nullable<double> SIEVE_3By8 { get; set; }
        public Nullable<double> SIEVE_4 { get; set; }
        public Nullable<double> SIEVE_10 { get; set; }
        public Nullable<double> SIEVE_40 { get; set; }
        public Nullable<double> SIEVE_80 { get; set; }
        public Nullable<double> SIEVE_200 { get; set; }
        public Nullable<short> Bowder { get; set; }
        public Nullable<double> Max11By2 { get; set; }
        public Nullable<double> Min_11By2 { get; set; }
        public Nullable<double> Max_1 { get; set; }
        public Nullable<double> Min_1 { get; set; }
        public Nullable<double> Max_3By4 { get; set; }
        public Nullable<double> Min_3By4 { get; set; }
        public Nullable<double> Max_1By2 { get; set; }
        public Nullable<double> Min_1By2 { get; set; }
        public Nullable<double> Max_3By8 { get; set; }
        public Nullable<double> Min_3By8 { get; set; }
        public Nullable<double> Max__4 { get; set; }
        public Nullable<double> Min__4 { get; set; }
        public Nullable<double> Max__10 { get; set; }
        public Nullable<double> Min__10 { get; set; }
        public Nullable<double> Max__40 { get; set; }
        public Nullable<double> Min__40 { get; set; }
        public Nullable<double> Max__80 { get; set; }
        public Nullable<double> Min__80 { get; set; }
        public Nullable<double> Max__200 { get; set; }
        public Nullable<double> Min__200 { get; set; }
        public Nullable<double> pb { get; set; }
        public Nullable<short> Approved { get; set; }
        public Nullable<int> LPrint { get; set; }
        public Nullable<float> aggfactor { get; set; }
        public string SupLocation { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Activate { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> JMFRequested { get; set; }
        public string JMFRequestedH { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
    }
}
