//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarshalAsphaltSpec
    {
        public int TypeNum { get; set; }
        public string item { get; set; }
        public Nullable<short> tasphalt { get; set; }
        public Nullable<short> basphalt { get; set; }
        public Nullable<short> stability { get; set; }
        public Nullable<short> lostability { get; set; }
        public Nullable<double> tflow { get; set; }
        public Nullable<double> bflow { get; set; }
        public Nullable<short> tairvoid { get; set; }
        public Nullable<short> bairvoid { get; set; }
        public Nullable<short> tfilvoid { get; set; }
        public Nullable<short> bfilvoid { get; set; }
        public Nullable<short> ts15 { get; set; }
        public Nullable<short> bs15 { get; set; }
        public Nullable<short> ts1 { get; set; }
        public Nullable<short> bs1 { get; set; }
        public Nullable<short> ts34 { get; set; }
        public Nullable<short> bs34 { get; set; }
        public Nullable<short> ts12 { get; set; }
        public Nullable<short> bs12 { get; set; }
        public Nullable<short> ts38 { get; set; }
        public Nullable<short> bs38 { get; set; }
        public Nullable<short> ts4 { get; set; }
        public Nullable<short> bs4 { get; set; }
        public Nullable<short> ts10 { get; set; }
        public Nullable<short> bs10 { get; set; }
        public Nullable<short> ts40 { get; set; }
        public Nullable<short> bs40 { get; set; }
        public Nullable<short> ts80 { get; set; }
        public Nullable<short> bs80 { get; set; }
        public Nullable<short> ts200 { get; set; }
        public Nullable<short> bs200 { get; set; }
    }
}
