//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialforBringVisit
    {
        public int id { get; set; }
        public Nullable<int> visit_id { get; set; }
        public string matrial_name { get; set; }
        public Nullable<int> qunatity { get; set; }
        public Nullable<bool> isRecieved { get; set; }
        public string notes { get; set; }
    }
}
