//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialResultsPdf
    {
        public int Id { get; set; }
        public Nullable<long> MixingDesignId { get; set; }
        public string PdfPath { get; set; }
        public string FileName { get; set; }
    
        public virtual ConcreteMixingDesign ConcreteMixingDesign { get; set; }
    }
}
