//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MixingDesignTest
    {
        public int ID { get; set; }
        public Nullable<long> MixingID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string FileName { get; set; }
        public string CompleteFileName { get; set; }
    
        public virtual ConcreteMixingDesign ConcreteMixingDesign { get; set; }
        public virtual TestsMixingDesign TestsMixingDesign { get; set; }
    }
}
