//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlyResult
    {
        public int id { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<int> areaLoaded { get; set; }
        public Nullable<double> unitWeight { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> crushingLoad { get; set; }
        public Nullable<double> CompressiveStrength { get; set; }
        public Nullable<double> averageCompressiveStrength { get; set; }
        public Nullable<int> sampleNumber { get; set; }
    }
}
