//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int PermitID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> PermitDate { get; set; }
        public Nullable<int> MuncipityId { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Street { get; set; }
        public Nullable<int> NoLayers { get; set; }
        public string ServiceType { get; set; }
        public string ExtensionType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> OuterLabId { get; set; }
        public Nullable<System.Guid> RelatedCompanyId { get; set; }
        public Nullable<int> PermitNumber { get; set; }
    }
}
