//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int ID { get; set; }
        public Nullable<int> PlantLocationId { get; set; }
        public string PlantName { get; set; }
        public string MapPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> PlantManagerId { get; set; }
    }
}
