//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureResistanceTestforFactorySample
    {
        public Nullable<double> SampleNo { get; set; }
        public Nullable<int> ConcreteRank { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> AreaLoaded { get; set; }
        public Nullable<double> UnitWeight { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> CrushingLoad { get; set; }
        public Nullable<double> CompressiveStrength { get; set; }
        public Nullable<double> AvgCompressiveStrength { get; set; }
        public string Result { get; set; }
        public int ID { get; set; }
    }
}
