//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QcSoilFieldsTest
    {
        public int ID { get; set; }
        public Nullable<int> PermitId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string Lat { get; set; }
        public string Lan { get; set; }
        public string LineName { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public Nullable<int> LayerNumber { get; set; }
        public Nullable<int> LayersNumber { get; set; }
        public string SampleType { get; set; }
        public string Classification { get; set; }
        public Nullable<double> Proctor { get; set; }
        public Nullable<double> GMB { get; set; }
        public Nullable<double> CompactionRatio { get; set; }
        public Nullable<bool> IsCompactionSuccess { get; set; }
        public Nullable<System.Guid> GehaId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public string LineType { get; set; }
        public string Street { get; set; }
        public string FailureReason { get; set; }
    }
}
