//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCWorkFlow
    {
        public int ID { get; set; }
        public Nullable<int> PermitId { get; set; }
        public Nullable<bool> IsPermitLocationTest { get; set; }
        public Nullable<System.DateTime> DateLocationTest { get; set; }
        public Nullable<bool> IsVisionTest { get; set; }
        public Nullable<System.DateTime> DateVisionTest { get; set; }
        public Nullable<bool> IsPermitAssignToLab { get; set; }
        public Nullable<bool> IsPermitAssignToRelatedCompany { get; set; }
        public Nullable<bool> IsPermitAssignedToAmana { get; set; }
        public Nullable<bool> IsVisionTestFailedCompany { get; set; }
        public Nullable<bool> IsVisionTestFailedAmana { get; set; }
        public Nullable<bool> IsLocationTestFailedAmana { get; set; }
        public Nullable<bool> IsPermitFinised { get; set; }
        public string FailedReason { get; set; }
    }
}
