//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportUpdateHistory
    {
        public int id { get; set; }
        public Nullable<bool> MixerNumber { get; set; }
        public Nullable<bool> TruckNumber { get; set; }
        public Nullable<bool> InvoiceNumber { get; set; }
        public Nullable<bool> ClientName { get; set; }
        public Nullable<bool> ConcreteRank { get; set; }
        public Nullable<bool> ConcreteTemperture { get; set; }
        public Nullable<bool> WaterTemperature { get; set; }
        public Nullable<bool> WeatherTemperture { get; set; }
        public Nullable<bool> DownAmount { get; set; }
        public Nullable<bool> CementType { get; set; }
        public Nullable<bool> CementSource { get; set; }
        public Nullable<bool> AdditionType { get; set; }
        public Nullable<bool> AdditionAmount { get; set; }
        public Nullable<bool> CementWeight { get; set; }
        public Nullable<bool> WaterWieght { get; set; }
        public Nullable<bool> WashedSandWeight { get; set; }
        public Nullable<bool> WhiteSandWeight { get; set; }
        public Nullable<bool> Rubble3by4 { get; set; }
        public Nullable<bool> Rubble3by8 { get; set; }
        public Nullable<bool> IsCleanUsage { get; set; }
        public Nullable<bool> IsBasicUsage { get; set; }
        public Nullable<bool> IsColumnUsage { get; set; }
        public Nullable<bool> IsRoofUsage { get; set; }
        public Nullable<bool> IsOtherUsage { get; set; }
        public Nullable<bool> IsCleanLocation { get; set; }
        public Nullable<bool> IsDustControlInStation { get; set; }
        public Nullable<bool> IsRokamSummer { get; set; }
        public Nullable<bool> IsLabEngineer { get; set; }
        public Nullable<bool> IsMoldanatInTrucks { get; set; }
        public Nullable<bool> IsPeopleSafty { get; set; }
        public Nullable<bool> InvoicePhoto { get; set; }
        public Nullable<bool> CleanDocPath { get; set; }
        public Nullable<bool> DustDocPath { get; set; }
        public Nullable<bool> SummerDocPath { get; set; }
        public Nullable<bool> LabDocPath { get; set; }
        public Nullable<bool> TruckDocPath { get; set; }
        public Nullable<bool> SafteyDocPath { get; set; }
        public Nullable<bool> OtherReason { get; set; }
        public Nullable<bool> CleanDocNote { get; set; }
        public Nullable<bool> DustDocNote { get; set; }
        public Nullable<bool> SummerDocNote { get; set; }
        public Nullable<bool> LabDocNote { get; set; }
        public Nullable<bool> TruckDocNote { get; set; }
        public Nullable<bool> SafteyDocNote { get; set; }
        public Nullable<bool> TempretureDocPath { get; set; }
        public Nullable<bool> DownAmountDocPath { get; set; }
        public Nullable<bool> concretemixPath { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> SampleNumber { get; set; }
        public string OldMixerNumber { get; set; }
        public string NewMixerNumber { get; set; }
        public string OldTruckNumber { get; set; }
        public string NewTruckNumber { get; set; }
        public string OldInvoiceNumber { get; set; }
        public string NewInvoiceNumber { get; set; }
        public string OldClientName { get; set; }
        public string NewClientName { get; set; }
        public string OldConcreteRank { get; set; }
        public string NewConcreteRank { get; set; }
        public Nullable<double> OldConcreteTemperture { get; set; }
        public Nullable<double> NewConcreteTemperture { get; set; }
        public Nullable<double> OldWaterTemperature { get; set; }
        public Nullable<double> NewWaterTemperature { get; set; }
        public Nullable<double> OldWeatherTemperture { get; set; }
        public Nullable<double> NewWeatherTemperture { get; set; }
        public Nullable<double> OldDownAmount { get; set; }
        public Nullable<double> NewDownAmount { get; set; }
        public string OldCementType { get; set; }
        public string NewCementType { get; set; }
        public string OldCementSource { get; set; }
        public string NewCementSource { get; set; }
        public string OldAdditionType { get; set; }
        public string NewAdditionType { get; set; }
        public string OldAdditionAmount { get; set; }
        public string NewAdditionAmount { get; set; }
        public Nullable<double> OldCementWeight { get; set; }
        public Nullable<double> NewCementWeight { get; set; }
        public Nullable<double> OldWaterWieght { get; set; }
        public Nullable<double> NewWaterWieght { get; set; }
        public Nullable<double> OldWashedSandWeight { get; set; }
        public Nullable<double> NewWashedSandWeight { get; set; }
        public Nullable<double> OldWhiteSandWeight { get; set; }
        public Nullable<double> NewWhiteSandWeight { get; set; }
        public Nullable<double> OldRubble3by4 { get; set; }
        public Nullable<double> NewRubble3by4 { get; set; }
        public Nullable<double> OldRubble3by8 { get; set; }
        public Nullable<double> NewRubble3by8 { get; set; }
        public Nullable<bool> OldIsCleanUsage { get; set; }
        public Nullable<bool> NewIsCleanUsage { get; set; }
        public Nullable<bool> OldIsBasicUsage { get; set; }
        public Nullable<bool> NewIsBasicUsage { get; set; }
        public Nullable<bool> OldIsColumnUsage { get; set; }
        public Nullable<bool> NewIsColumnUsage { get; set; }
        public Nullable<bool> OldIsRoofUsage { get; set; }
        public Nullable<bool> NewIsRoofUsage { get; set; }
        public Nullable<bool> OldIsOtherUsage { get; set; }
        public Nullable<bool> NewIsOtherUsage { get; set; }
        public Nullable<bool> OldIsCleanLocation { get; set; }
        public Nullable<bool> NewIsCleanLocation { get; set; }
        public Nullable<bool> OldIsDustControlInStation { get; set; }
        public Nullable<bool> NewIsDustControlInStation { get; set; }
        public Nullable<bool> OldIsRokamSummer { get; set; }
        public Nullable<bool> NewIsRokamSummer { get; set; }
        public Nullable<bool> OldIsLabEngineer { get; set; }
        public Nullable<bool> NewIsLabEngineer { get; set; }
        public Nullable<bool> OldIsMoldanatInTrucks { get; set; }
        public Nullable<bool> NewIsMoldanatInTrucks { get; set; }
        public Nullable<bool> OldIsPeopleSafty { get; set; }
        public Nullable<bool> NewIsPeopleSafty { get; set; }
        public string OldInvoicePhoto { get; set; }
        public string NewInvoicePhoto { get; set; }
        public string OldCleanDocPath { get; set; }
        public string NewCleanDocPath { get; set; }
        public string OldDustDocPath { get; set; }
        public string NewDustDocPath { get; set; }
        public string OldSummerDocPath { get; set; }
        public string NewSummerDocPath { get; set; }
        public string OldLabDocPath { get; set; }
        public string NewLabDocPath { get; set; }
        public string OldTruckDocPath { get; set; }
        public string NewTruckDocPath { get; set; }
        public string OldSafteyDocPath { get; set; }
        public string NewSafteyDocPath { get; set; }
        public string OldOtherReason { get; set; }
        public string NewOtherReason { get; set; }
        public string OldCleanDocNote { get; set; }
        public string NewCleanDocNote { get; set; }
        public string OldDustDocNote { get; set; }
        public string NewDustDocNote { get; set; }
        public string OldSummerDocNote { get; set; }
        public string NewSummerDocNote { get; set; }
        public string OldLabDocNote { get; set; }
        public string NewLabDocNote { get; set; }
        public string OldTruckDocNote { get; set; }
        public string NewTruckDocNote { get; set; }
        public string OldSafteyDocNote { get; set; }
        public string NewSafteyDocNote { get; set; }
        public string OldTempretureDocPath { get; set; }
        public string NewTempretureDocPath { get; set; }
        public string OldDownAmountDocPath { get; set; }
        public string NewDownAmountDocPath { get; set; }
        public string OldconcretemixPath { get; set; }
        public string NewconcretemixPath { get; set; }
        public string MonitorName { get; set; }
    }
}
