//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportResult
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public bool Status { get; set; }
        public int FactoryId { get; set; }
        public int FactoryReportId { get; set; }
    
        public virtual Factory11 Factory { get; set; }
        public virtual FactoryEvaluationReport FactoryEvaluationReport { get; set; }
    }
}
