//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptVPeriodic
    {
        public int ClsYear { get; set; }
        public int FactoryId { get; set; }
        public int ConClsPeriodicLabPropertId { get; set; }
        public Nullable<int> ConClsLabPropertyId { get; set; }
        public string PropertyText { get; set; }
        public Nullable<int> ConClsCategoryId { get; set; }
        public string Peroidic { get; set; }
        public int ID { get; set; }
    }
}
