//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplesWorkFlow
    {
        public int ID { get; set; }
        public Nullable<int> SampleNo { get; set; }
        public Nullable<int> GeneralSampleTypeId { get; set; }
        public Nullable<System.DateTime> InspectorManagerAssigned { get; set; }
        public Nullable<bool> InspectorManager { get; set; }
        public Nullable<bool> InspectorConfirm { get; set; }
        public Nullable<System.DateTime> InspectorConfirmed { get; set; }
        public Nullable<System.DateTime> Receptioned { get; set; }
        public Nullable<bool> Reception { get; set; }
        public Nullable<System.DateTime> Compactioned { get; set; }
        public Nullable<bool> Compaction { get; set; }
        public Nullable<System.DateTime> Tested { get; set; }
        public Nullable<bool> Test { get; set; }
        public Nullable<System.DateTime> Printed { get; set; }
        public Nullable<bool> Print { get; set; }
        public Nullable<System.DateTime> MarshalJmRequested { get; set; }
        public Nullable<bool> MarshalJmRequest { get; set; }
        public Nullable<bool> IsReceptionManually { get; set; }
        public string RequestNumber { get; set; }
    }
}
