//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleCubePath
    {
        public int ID { get; set; }
        public Nullable<double> SampleNumber { get; set; }
        public string Cube1P1 { get; set; }
        public string Cube1P2 { get; set; }
        public string Cube2P1 { get; set; }
        public string Cube2P2 { get; set; }
        public string Cube3P1 { get; set; }
        public string Cube3P2 { get; set; }
    }
}
