//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoilDesign
    {
        public int SoilTypeId { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T15F { get; set; }
        public Nullable<double> T15T { get; set; }
        public Nullable<double> T1F { get; set; }
        public Nullable<double> T1T { get; set; }
        public Nullable<double> T34T { get; set; }
        public Nullable<double> T34F { get; set; }
        public Nullable<double> T5F { get; set; }
        public Nullable<double> T5T { get; set; }
        public Nullable<double> T38F { get; set; }
        public Nullable<double> T38T { get; set; }
        public Nullable<double> T4F { get; set; }
        public Nullable<double> T4T { get; set; }
        public Nullable<double> T10F { get; set; }
        public Nullable<double> T10T { get; set; }
        public Nullable<double> T20F { get; set; }
        public Nullable<double> T20T { get; set; }
        public Nullable<double> T40F { get; set; }
        public Nullable<double> T40T { get; set; }
        public Nullable<double> T80F { get; set; }
        public Nullable<double> T80T { get; set; }
        public Nullable<double> T200F { get; set; }
        public Nullable<double> T200T { get; set; }
    }
}
