//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoilMoisture
    {
        public int SampleNo { get; set; }
        public Nullable<double> Moist1 { get; set; }
        public Nullable<double> Moist2 { get; set; }
        public Nullable<double> Moist3 { get; set; }
        public Nullable<double> MoistureCont { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
    }
}
