//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoilResult
    {
        public int SampleNo { get; set; }
        public Nullable<double> SieveOne { get; set; }
        public Nullable<double> SieveOneAndHalf { get; set; }
        public Nullable<double> SieveThreeByFour { get; set; }
        public Nullable<double> SieveThreeBYEight { get; set; }
        public Nullable<double> SieveFour { get; set; }
        public Nullable<double> SieveThree { get; set; }
        public Nullable<double> SieveTeen { get; set; }
        public Nullable<double> SieveTwoHandreed { get; set; }
        public Nullable<double> SieveTwo { get; set; }
        public Nullable<double> SieveForty { get; set; }
        public Nullable<double> SieveHalf { get; set; }
        public Nullable<double> SieveTwenty { get; set; }
        public Nullable<double> SieveEighteen { get; set; }
        public Nullable<int> NoBlows { get; set; }
        public Nullable<double> NoLayers { get; set; }
        public Nullable<double> MaxDryDensity { get; set; }
        public Nullable<double> MoistureContent { get; set; }
        public Nullable<double> Liquidlimit { get; set; }
        public Nullable<double> PlasticLimit { get; set; }
        public Nullable<double> PlasticityIndex { get; set; }
        public Nullable<double> GroupIndex { get; set; }
        public string SoilClassification { get; set; }
        public Nullable<double> MoistureInLocation { get; set; }
        public Nullable<double> CompactionRatioInLocation { get; set; }
        public Nullable<double> MC1 { get; set; }
        public Nullable<double> MC2 { get; set; }
        public Nullable<double> MC3 { get; set; }
        public Nullable<double> MC4 { get; set; }
        public Nullable<double> MC5 { get; set; }
        public Nullable<double> DR1 { get; set; }
        public Nullable<double> DR2 { get; set; }
        public Nullable<double> DR3 { get; set; }
        public Nullable<double> DR4 { get; set; }
        public Nullable<double> DR5 { get; set; }
    }
}
