//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperPaveSampleResult
    {
        public int SampleNo { get; set; }
        public Nullable<double> ACPercent { get; set; }
        public Nullable<double> Gmm { get; set; }
        public Nullable<double> Gmmb { get; set; }
        public Nullable<double> GmmPercent { get; set; }
        public Nullable<double> AVpercent { get; set; }
        public Nullable<double> SieveOne { get; set; }
        public Nullable<double> SieveOneAndHalf { get; set; }
        public Nullable<double> SieveThreeByFour { get; set; }
        public Nullable<double> SieveHalf { get; set; }
        public Nullable<double> SieveThreeBYEight { get; set; }
        public Nullable<double> SieveFour { get; set; }
        public Nullable<double> SieveEight { get; set; }
        public Nullable<double> SieveSixteen { get; set; }
        public Nullable<double> SieveThirty { get; set; }
        public Nullable<double> SieveFifteen { get; set; }
        public Nullable<double> SieveHandreed { get; set; }
        public Nullable<double> SieveTwoHandreed { get; set; }
    }
}
