//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperPaveMixDesign
    {
        public int ID { get; set; }
        public Nullable<byte> MixType { get; set; }
        public string DesignTrafficClass { get; set; }
        public string TrafficSpeed { get; set; }
        public string LayerThickness { get; set; }
        public string NominalMaximumSize { get; set; }
        public string AsphaltBinder { get; set; }
        public string UsedBinderModifier { get; set; }
        public Nullable<double> SieveOneAndHalfPass { get; set; }
        public Nullable<double> SieveOnePass { get; set; }
        public Nullable<double> SieveEightPass { get; set; }
        public Nullable<double> SieveThreeByFourPass { get; set; }
        public Nullable<double> SieveHalfPass { get; set; }
        public Nullable<double> SiveThreeByEightPass { get; set; }
        public Nullable<double> SieveFourPass { get; set; }
        public Nullable<double> SieveSixTeenPass { get; set; }
        public Nullable<double> SieveThrityPass { get; set; }
        public Nullable<double> SieveFifteenPass { get; set; }
        public Nullable<double> SieveHandreedPass { get; set; }
        public Nullable<double> SiveTwoHandreedPass { get; set; }
        public Nullable<double> SieveOneAndHalfToleranceFrom { get; set; }
        public Nullable<double> SieveOneAndHalfToleranceTo { get; set; }
        public Nullable<double> SieveOneToleranceFrom { get; set; }
        public Nullable<double> SieveOneToleranceTo { get; set; }
        public Nullable<double> SieveThreeByFourToleranceFrom { get; set; }
        public Nullable<double> SieveThreeByFourToleranceTo { get; set; }
        public Nullable<double> SieveHalfToleranceFrom { get; set; }
        public Nullable<double> SieveHalfToleranceTo { get; set; }
        public Nullable<double> SiveThreeByEightToleranceFrom { get; set; }
        public Nullable<double> SiveThreeByEightToleranceTo { get; set; }
        public Nullable<double> SieveFourToleranceFrom { get; set; }
        public Nullable<double> SieveFourToleranceTo { get; set; }
        public Nullable<double> SieveSixTeenToleranceFrom { get; set; }
        public Nullable<double> SieveSixTeenToleranceTo { get; set; }
        public Nullable<double> SieveThrityToleranceFrom { get; set; }
        public Nullable<double> SieveThrityToleranceTo { get; set; }
        public Nullable<double> SieveFifteenToleranceFrom { get; set; }
        public Nullable<double> SieveFifteenToleranceTo { get; set; }
        public Nullable<double> SieveHundreedToleranceTo { get; set; }
        public Nullable<double> SieveHandreedToleranceFrom { get; set; }
        public Nullable<double> SiveTwoHandreedToleranceFrom { get; set; }
        public Nullable<double> SieveEightToleranceTo { get; set; }
        public Nullable<double> SieveEightToleranceFrom { get; set; }
        public Nullable<double> SiveTwoHandreedToleranceTo { get; set; }
        public Nullable<double> ACPercentFrom { get; set; }
        public Nullable<double> ACPercentTo { get; set; }
        public Nullable<double> AVPercentFrom { get; set; }
        public Nullable<double> AVPercentTo { get; set; }
        public Nullable<double> GMMInitalPercentFrom { get; set; }
        public Nullable<double> GMMInitalPercentTo { get; set; }
        public Nullable<double> GMMDesTo { get; set; }
        public Nullable<double> GMMDesFrom { get; set; }
        public Nullable<double> GMMmaxPercentFrom { get; set; }
        public Nullable<double> GMMmaxPercentTo { get; set; }
        public string LAAbrasion { get; set; }
        public string FAAngularity { get; set; }
        public string SandEquivalent { get; set; }
        public string Soundness { get; set; }
        public Nullable<System.DateTime> AprovedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
    }
}
