//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspnetMvcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitDetail
    {
        public long Id { get; set; }
        public int FactoryId { get; set; }
        public int MonitorId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> visitpriority { get; set; }
    }
}
